<?php

require_once 'iondry.node.inc';



function iondry_preprocess_node(&$vars) {
  //theme hook suggestion based on view mode & type in combination
  $vars['theme_hook_suggestions'][] = 'node__' . $vars['view_mode'];
  $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__' . $vars['view_mode'];
}


function iondry_preprocess_field(&$vars) {
  $element = $vars['element'];

  //theme hook suggestion based on view mode & type in combination
  $vars['theme_hook_suggestions'][] = 'field__' . $element['#field_name'] . '__' . $element['#bundle'] . '__' . $element['#view_mode'];
}
